window.whiskies = [
    {
        name: "Cardhu Gold Reserve Single Malt Scotch Whisky",
        description: "",
        brand: "Cardhu",
        age: 0,
        image: "gold-reserve.jpg",
        price: 30,
        type: "Single Malt",
        review: '',
        rating: 0,
        flavour: "Peaty & Smoky",
        flagIcon: "gb",
        country: "Scotland",
        region: "Lowlands",
        bottleCount: 1,
        caskType: "",
    },
    {
        name: "Glen Moray Single Malt Scotch Whisky",
        description: "",
        brand: "Glen Moray",
        age: 0,
        image: "glen-moray-elgin-classic-whisky.webp",
        price: 40,
        type: "Single Malt",
        review: '',
        rating: 0,
        flavour: "Rich & Sweet",
        flagIcon: "gb",
        country: "Scotland",
        region: "Speyside",
        bottleCount: 1,
        caskType: "",
    },
    {
        name: "Woodsman",
        description: "Blended Scotch Whisky",
        brand: "Woodsman",
        age: 0,
        image: "woodsman.jpg",
        price: 30,
        type: "Blended Whisky",
        review: '',
        rating: 2.5,
        flavour: "",
        flagIcon: "gb",
        country: "",
        region: "",
        bottleCount: 1,
        caskType: "double-scorched bourbon barrels",
    },
    {
        name: "Clubman",
        description: "Signle Grain Scotch Whisky",
        brand: "Clubman",
        age: 0,
        image: "clubman.jpeg",
        price: 25,
        type: "Grain Whisky",
        review: '',
        rating: 1,
        flavour: "",
        flagIcon: "gb",
        country: "",
        region: "Lowland",
        bottleCount: 1,
        caskType: "",
    },
    {
        name: "Woodford",
        description: "Reserve Kentucky Straight Bourbon Whiskey",
        brand: "Woodford",
        age: 0,
        image: "woodford.jpeg",
        price: 35,
        type: "Bourbon Whiskey",
        review: '',
        rating: 3,
        flavour: "",
        flagIcon: "us",
        country: "United States",
        region: "Kentucky",
        bottleCount: 1,
        caskType: "",
    },
    {
        name: "Glenfiddich 12 Year Old Whisky",
        description: "",
        brand: "Glenfiddich",
        age: 12,
        image: "glenfiddich-12-year-old-whisky.webp",
        price: 40,
        type: "Single Malt Whisky",
        review: '',
        rating: 2.5,
        flavour: "",
        flagIcon: "us",
        country: "United States",
        region: "Kentucky",
        bottleCount: 1,
        caskType: "",
    },
]