window.brands = [
    {
        name: "Cardhu",
        logo: "cardhu.png",
    },
    {
        name: "Glen Moray",
        logo: "glen-moray.png",
    },
    {
        name: "Woodsman",
        logo: "woodsman.png",
    },
    {
        name: "Clubman",
        logo: "clubman.png",
    },
    {
        name: "Woodford",
        logo: "woodford.png",
    },
    {
        name: "Glenfiddich",
        logo: "glenfiddich.png",
    },
    {
        name: "GlenAllachie",
        logo: "glenallachie.png",
    },
    {
        name: "Lagg",
        logo: "lagg.png",
    },
    {
        name: "Monkey Shoulder",
        logo: "monkey-shoulder.png",
    }
];

window.whiskies = [
    {
        name: "Cardhu Gold Reserve Single Malt Scotch Whisky",
        description: "",
        brand: "Cardhu",
        age: 0,
        image: "gold-reserve.jpg",
        price: 30,
        type: "Single Malt",
        review: '',
        rating: 3,
        flavour: "",
        flagIcon: "gb",
        country: "Scotland",
        region: "Speyside",
        bottleCount: 1,
        caskType: "",
        link: "https://www.masterofmalt.com/whiskies/cardhu/cardhu-gold-reserve-whisky/",
        wishlist: false,
        purchased: '2024-11-21'
    },
    {
        name: "Glen Moray Single Malt Scotch Whisky",
        description: "",
        brand: "Glen Moray",
        age: 0,
        image: "glen-moray-elgin-classic-whisky.webp",
        price: 20,
        type: "Single Malt",
        review: '',
        rating: 3,
        flavour: "Rich & Sweet",
        flagIcon: "gb",
        country: "Scotland",
        region: "Speyside",
        bottleCount: 1,
        caskType: "",
        link: "https://www.masterofmalt.com/whiskies/glen-moray/glen-moray-elgin-classic-whisky/",
        wishlist: false,
        purchased: '2024-11-21'
    },
    {
        name: "Woodsman",
        description: "Blended Scotch Whisky",
        brand: "Woodsman",
        age: 0,
        image: "woodsman.jpg",
        price: 30,
        type: "Blended Whisky",
        review: '',
        rating: 2.5,
        flavour: "",
        flagIcon: "gb",
        country: "",
        region: "",
        bottleCount: 1,
        caskType: "double-scorched bourbon barrels",
        link: "https://www.masterofmalt.com/whiskies/the-woodsman/the-woodsman-whisky/",
        wishlist: false,
    },
    {
        name: "Clubman",
        description: "Signle Grain Scotch Whisky",
        brand: "Clubman",
        age: 0,
        image: "clubman.jpeg",
        price: 25,
        type: "Grain Whisky",
        review: '',
        rating: 1,
        flavour: "",
        flagIcon: "gb",
        country: "Scotland",
        region: "Lowland",
        bottleCount: 1,
        caskType: "",
        link: "https://www.masterofmalt.com/whiskies/haig/haig-club-clubman-whisky/",
        wishlist: false,
    },
    {
        name: "Woodford",
        description: "Reserve Kentucky Straight Bourbon Whiskey",
        brand: "Woodford",
        age: 0,
        image: "woodford.jpeg",
        price: 35,
        type: "Bourbon Whiskey",
        review: '',
        rating: 3,
        flavour: "",
        flagIcon: "us",
        country: "United States",
        region: "Kentucky",
        bottleCount: 1,
        caskType: "",
        link: "https://www.masterofmalt.com/whiskies/woodford-reserve/woodford-reserve-kentucky-bourbon-whiskey/",
        wishlist: false,
    },
    {
        name: "Glenfiddich 12 Year Old Whisky",
        description: "",
        brand: "Glenfiddich",
        age: 12,
        image: "glenfiddich-12-year-old-whisky.webp",
        price: 40,
        type: "Single Malt",
        review: '',
        rating: 2.5,
        flavour: "",
        flagIcon: "gb",
        country: "Scotland",
        region: "Speyside",
        bottleCount: 1,
        caskType: "",
        link: "https://www.masterofmalt.com/whiskies/glenfiddich-12-year-old-whisky/",
        wishlist: false,
    },
    {
        name: "Glenfiddich 12 Year Old American Oak Whisky",
        description: "",
        brand: "Glenfiddich",
        age: 12,
        image: "glenfiddich-12-year-old-american-oak-whisky.jpg",
        price: 45,
        type: "Single Malt",
        review: '',
        rating: 0,
        flavour: "",
        flagIcon: "gb",
        country: "Scotland",
        region: "Speyside",
        bottleCount: 0,
        caskType: "",
        link: "https://www.masterofmalt.com/whiskies/glenfiddich/glenfiddich-12-year-old-american-oak-whisky/",
        wishlist: true,
    },
    {
        name: "Glen Moray Twisted Vine WhiskyGlen Moray Twisted Vine Whisky",
        description: "",
        brand: "Glen Moray",
        age: 'N/A',
        image: "glen-moray-twisted-vine-whisky.webp",
        price: 30,
        type: "Single Malt",
        review: '',
        rating: 0,
        flavour: "",
        flagIcon: "gb",
        country: "Scotland",
        region: "Speyside",
        bottleCount: 0,
        caskType: "",
        link: "https://www.masterofmalt.com/whiskies/glenfiddich/glenfiddich-12-year-old-american-oak-whisky/",
        wishlist: true,
    },
    {
        name: "The Glenlivet Caribbean Reserve",
        description: "(Rum Barrel Selection)",
        brand: "Glenlivet",
        age: 'N/A',
        image: "glenlivet-caribbean-rum.jpg",
        price: 26,
        type: "Single Malt",
        review: '',
        rating: 0,
        flavour: "",
        flagIcon: "gb",
        country: "Scotland",
        region: "Speyside",
        bottleCount: 0,
        caskType: "",
        link: "https://www.amazon.co.uk/gp/product/B08H6JBMR2/ref=ewc_pr_img_1?smid=A3P5ROKL5A1OLE&psc=1",
        wishlist: true,
    },
    {
        name: "GlenAllachie Meikle Toir",
        description: "(The Chinquapin One)",
        brand: "GlenAllachie",
        age: 'N/A',
        image: "meikle-toir-the-chinquapin-one-whisky.webp",
        price: 95,
        type: "Single Malt",
        review: '',
        rating: 0,
        flavour: "",
        flagIcon: "gb",
        country: "Scotland",
        region: "Speyside",
        bottleCount: 0,
        caskType: "",
        link: "https://www.masterofmalt.com/whiskies/glenallachie/meikle-toir-the-chinquapin-one-whisky/",
        wishlist: true,
    },
    {
        name: "Lagg Corriecravie",
        description: "(The Arran Malt)",
        brand: "Lagg",
        age: 'N/A',
        image: "lagg-corriecravie-whisky.webp",
        price: 65,
        type: "Single Malt",
        review: '',
        rating: 0,
        flavour: "",
        flagIcon: "gb",
        country: "Scotland",
        region: "Island",
        bottleCount: 0,
        caskType: "",
        link: "https://www.masterofmalt.com/whiskies/lagg/lagg-corriecravie-whisky/",
        wishlist: true,
    },
    {
        name: "Monkey Shoulder",
        description: "Blended Scotch Whisky",
        brand: "Monkey Shoulder",
        age: 'N/A',
        image: "monkey-shoulder-blended-scotch-whisky.webp",
        price: 30,
        type: "Blended Whisky",
        review: '',
        rating: 0,
        flavour: "",
        flagIcon: "gb",
        country: "",
        region: "",
        bottleCount: 0,
        caskType: "",
        link: "https://www.masterofmalt.com/whiskies/monkey-shoulder-blended-scotch-whisky/",
        wishlist: true,
    }
]